---
title: "Hjälp"
author: "xploR"
date: "22 oktober 2015"
output: html_document
runtime: shiny
---

För en kort introduktion om hur du använder xploR, [klicka här](#intro). 

För övriga vanliga frågor, [klicka här](#faq). 

### <a name = "intro"></a>Introduktion

Text...

### <a name = "faq"></a>Vanliga frågor

Nedan kan du läsa de vanliga frågorna och svaren om xploR. Om du söker svaret på en fråga som du inte hittar på den här sidan, kan du använda kontaktformuläret som du hittar [här](). 

**Vad är syftet med xploR?**

xploR ingår i ett forskningsprojekt som syftar till att utveckla nya metoder och verktyg för större delaktighet i offentliga beslutprocesser. Du kan läsa mer om projektet [här](http://dsv.su.se/en/research/research-areas/egovern/projects/multimodal-1.113056). 

**Vem står bakom xploR?**

xploR är utvecklad på Institutionen för data- och systemvetenskap (DSV) vid Stockholms universitet [^1] i samarbete med Skolan för arkitektur och samhällsbyggande (ABE) vid Kunglika Tekniska högskolan [^2] och Upplands Väsby kommun [^3]. 

**Vilka är de tekniska kraven för att använda xploR?**

Du behöver en dator med en uppdaterad webbläsare installerad, t.ex. Chrome, Firefox, Safari, Internet Explorer, eller Edge. 

**Vilken data finns i xploR?**

xploR redovisar resultaten av en webbenkät som genomfördes i Upplands Väsby kommun i början av 2015. Enkäten hade rubriken "Vad tycker du att Upplands Väsby ska satsa på i framtiden?" och bestod av 23 frågor uppdelade i tio teman. För att läsa mer om enkäten, [klicka här](). 

**Varifrån kommer namnet xploR?**

Namnet xploR kommer från begreppet explorativ dataanalys (EDA) som är samling grafiska metoder inom den beskrivande statistiken. EDA går ut på att utforska data visuellt för att upptäcka mönster, trender och avvikelser i de fenomen som studeras. 

**Kan jag ladda ned datan?**

Ja, [här](). 

[^1]: http://dsv.su.se/
[^2]: http://www.kth.se/abe/
[^3]: http://www.upplandsvasby.se/




